# File: docker-compose.yml
# 5.3 Kết hợp frontend, backend, MongoDB containers

version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - mongodb+srv://22521082:phongpro@cluster0.v4wza.mongodb.net/Go_edu?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_HOST= redis-13556.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com
      - REDIS_PORT= 13556
      - REDIS_PASS= sNTEWs4K9aRsbWViAkufgrCxtnlFRCu8
      # Nếu sử dụng MongoDB Atlas, thay dòng trên thành:
      # - MONGODB_URI=mongodb+srv://22521082:phongpro@cluster0.v4wza.mongodb.net/Go_edu?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
  redis-data: